// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaODvrLglgUgx86y6FcKz4LxvK8OvQ0O8',
    appId: '1:701929335375:web:b8efa538386589ffd7d83a',
    messagingSenderId: '701929335375',
    projectId: 'authomnimuse-bc130',
    authDomain: 'authomnimuse-bc130.firebaseapp.com',
    storageBucket: 'authomnimuse-bc130.appspot.com',
    measurementId: 'G-3D6B5JX1ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9okIpHnorlZoR3NtdKfXdH0Zyu9u1OJM',
    appId: '1:701929335375:android:41ac2385944cc18cd7d83a',
    messagingSenderId: '701929335375',
    projectId: 'authomnimuse-bc130',
    storageBucket: 'authomnimuse-bc130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATpnk1CgxXIObF-RkGKNXnxP9LLtX_c14',
    appId: '1:701929335375:ios:4bb2a49cf82cff53d7d83a',
    messagingSenderId: '701929335375',
    projectId: 'authomnimuse-bc130',
    storageBucket: 'authomnimuse-bc130.appspot.com',
    iosBundleId: 'com.example.omnimuse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATpnk1CgxXIObF-RkGKNXnxP9LLtX_c14',
    appId: '1:701929335375:ios:67cde99dfd281165d7d83a',
    messagingSenderId: '701929335375',
    projectId: 'authomnimuse-bc130',
    storageBucket: 'authomnimuse-bc130.appspot.com',
    iosBundleId: 'com.example.omnimuse.RunnerTests',
  );
}
